### ISSUE TITLE
Create a Liferay theme that implements the Italia Design Guidelines

### ISSUE THREAD

**Issue by ruphy** [italia/design-liferay-theme#1]
Create a theme for Liferay based on the [User Interface design guidelines](
https://design-italia.readthedocs.io/it/stable/doc/user-interface.html).

Do include [the design web toolkit](https://github.com/italia/design-web-toolkit) as a dependency, and make sure you write your code in a way which is generic enough so that, later on, it be replaced by another toolkit (e.g. bootstrap) without too much effort.

Some example websites with the correct style
https://developers.italia.it
https://designers.italia.it

**Comment by DavidePastore** [comment]
What is the target version of Liferay for which develop the theme?

**Comment by ruphy** [comment]
Hi,
there is not a precise version which we are trying to target: the more users will use this theme, the better. The best thing is to target multiple versions, or at least the most used ones, in a compatible way. In case of incompatibilities we can also have multiple liferay themes developed. If you want to contribute, feel free to submit more than one PR, or one with multiple subdirectories!

**Comment by ruphy** [comment]
closed by #2
